//! Config loading. Looks at `~/.config/construct/config.toml`, merging built-in
//! adapter defaults underneath.

use construct_protocol::paths::Paths;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

/// Env override for the playbook-templates directory. Wins over the
/// `[playbook].templates_dir` config option; both fall back to the default
/// `data_dir/playbook/templates`.
pub const PLAYBOOK_TEMPLATES_DIR_ENV: &str = "CONSTRUCT_PLAYBOOK_TEMPLATES_DIR";

/// The full config template written to `config.toml.template` on every daemon
/// start. All configurable parameters are listed with their default values and
/// explanatory comments. The daemon always overwrites this file so it stays
/// current when construct is upgraded.
///
/// Also surfaced by `construct daemon default-config` for scripted inspection.
pub const CONFIG_TOML_TEMPLATE: &str = r#"# construct configuration template
# Generated by the daemon on startup — always reflects the current version.
# This file is overwritten on every daemon start; edit config.toml instead.
#
# Active config:  ~/.config/construct/config.toml  (or $CONSTRUCT_CONFIG_DIR/config.toml)
# This template:  ~/.config/construct/config.toml.template
#
# All built-in adapters (shell, claude, codex, opencode, antigravity, grok, kimi, hermes, pi, smith) are
# registered automatically — you do not need to declare them unless you want
# to change a field.

# ── Adapters ─────────────────────────────────────────────────────────────────
#
# Each [adapters.<name>] entry registers or overrides a harness. The daemon
# locates the binary next to itself or via PATH; use `binary` to pin an
# absolute path.
#
# Built-in adapters registered automatically (no config required):
#   shell       — generic shell command runner
#   claude      — Claude Code
#   codex       — OpenAI Codex
#   opencode    — OpenCode
#   antigravity — Google Antigravity
#   grok        — Grok CLI
#   kimi        — Kimi Code
#   hermes      — Hermes Agent
#   pi          — pi coding agent
#   smith       — native multi-provider agent (OpenAI / Anthropic / Gemini / Meta / Ollama / Grok)

# [adapters.shell]
# binary      = "construct"                 # default: resolved from PATH / next to daemon
# args        = ["__adapter", "shell"]      # default: built-in dispatch args
# description = "Generic shell command runner"  # shown in harness picker

# [adapters.claude]
# binary      = "construct"
# args        = ["__adapter", "claude"]
# description = "Claude Code"

# [adapters.codex]
# binary      = "construct"
# args        = ["__adapter", "codex"]
# description = "OpenAI Codex"

# [adapters.opencode]
# binary      = "construct"
# args        = ["__adapter", "opencode"]
# description = "OpenCode"

# [adapters.agy]
# binary      = "construct"
# args        = ["__adapter", "agy"]
# description = "Google Antigravity"

# [adapters.grok]
# binary      = "construct"
# args        = ["__adapter", "grok"]
# description = "Grok CLI"

# [adapters.smith]
# binary      = "construct"
# args        = ["__adapter", "smith"]
# description = "Built-in multi-provider agent (OpenAI / Anthropic / Gemini / Meta / Ollama / Grok)"

# Per-harness environment variables ──────────────────────────────────────────
#
# `env` is a table of key = "value" pairs merged into every session spawned
# under this harness. Lets operators set per-harness defaults (e.g. a default
# model) from config.toml without exporting vars in the shell that starts the
# daemon. Per-session `construct new --env KEY=VAL` takes precedence.
#
# Smith model selection (pick one, or omit if ANTHROPIC_API_KEY / OPENAI_API_KEY /
# GEMINI_API_KEY (or GOOGLE_API_KEY) / META_API_KEY (or MODEL_API_KEY) is set in
# the daemon's environment — smith auto-detects those four, in that order. Without
# a pin AND without one of those four set, smith fails to start rather than falling back
# to a local Ollama that may not be running. OAuth subscriptions and Ollama always
# need an explicit pin here (or --model / CONSTRUCT_SMITH_MODEL per-session) since
# there's no way to auto-detect them safely. The construct TUI's `/configure`
# dialog (smith-auth tab) writes this same key for you after showing live status
# for every method below.
#
# [adapters.smith.env]
# CONSTRUCT_SMITH_MODEL = "anthropic:claude-sonnet-4-6"   # direct API via ANTHROPIC_API_KEY
# # CONSTRUCT_SMITH_MODEL = "claude-oauth:claude-sonnet-4-6"  # via Claude subscription
# # CONSTRUCT_SMITH_MODEL = "openai:gpt-5.5"                  # direct API via OPENAI_API_KEY
# # CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5"             # via OpenAI subscription
# # CONSTRUCT_SMITH_MODEL = "grok-oauth:grok-2-latest"        # via Grok subscription
# # CONSTRUCT_SMITH_MODEL = "kimi-oauth:k3"                    # via Kimi subscription
# # CONSTRUCT_SMITH_MODEL = "gemini:gemini-2.5-pro"           # via GEMINI_API_KEY
# # CONSTRUCT_SMITH_MODEL = "meta:muse-spark-1.1"             # via META_API_KEY / MODEL_API_KEY
# # CONSTRUCT_SMITH_MODEL = "ollama:llama3.1"                 # local Ollama server
# # CONSTRUCT_SMITH_MODEL = "@deepseek"                       # named profile (see [smith.models.*])

# Override the CLI binary a built-in adapter launches. CONSTRUCT_*_CMD is split
# shell-style (quotes/backslashes only; no shell expansion) and prepended before
# the adapter's generated arguments. Wins over the binary-only CONSTRUCT_*_BIN.
#
# [adapters.codex.env]
# CONSTRUCT_CODEX_CMD = "exec codex"        # also: CONSTRUCT_CLAUDE_CMD, CONSTRUCT_OPENCODE_CMD, CONSTRUCT_SHELL_CMD, CONSTRUCT_ANTIGRAVITY_CMD, CONSTRUCT_GROK_CMD, CONSTRUCT_KIMI_CMD

# Usage-probe command ────────────────────────────────────────────────────────
#
# `usage_probe` is the interactive slash command the daemon sends to a
# short-lived ephemeral session to capture this harness's own usage/status
# panel (spec 0086), cached for 5 minutes and surfaced as a hover tooltip.
# The raw rendered output is captured and redisplayed verbatim — never
# parsed into token counts or other structured fields.
#
# Unset (the default): the harness's built-in usage command runs —
#   claude -> "/usage", codex -> "/status", agy -> "/usage", grok -> "/usage show".
# Empty string: disables the probe entirely for this harness.
# Any other string: sent verbatim instead of the built-in default.
#
# [adapters.claude]
# usage_probe = "/usage"     # same as the built-in default; shown for discoverability
#
# [adapters.codex]
# usage_probe = ""           # disable the usage probe for codex

# Community / custom adapters — any binary that speaks the AHP protocol:
#
# [adapters.aider]
# binary      = "construct-adapter-aider"
# description = "Aider (community adapter)"
#
# Installed plugins (`construct plugin install owner/repo`, spec 0152)
# register their adapters automatically — no [adapters.*] block needed. A
# block naming a plugin harness (e.g. [adapters."my-plugin:tool"]) still
# works to override individual fields; your values win field-by-field.

# ── Defaults ─────────────────────────────────────────────────────────────────

[defaults]
# When true, every new session whose cwd is a git repo gets its own isolated
# git worktree. Override per session with `construct new ... --worktree`.
# Default: false
worktree = false

# ── Orchestrator (minibuffer) ─────────────────────────────────────────────────
#
# The orchestrator is a persistent smith session rendered as the minibuffer
# at the bottom of the TUI. It receives fleet-wide events and can dispatch
# commands to other sessions.

[orchestrator]
# Which harness backs the orchestrator session. Set to "" or use enabled =
# false to disable the orchestrator entirely — clients fall back to the
# static command palette.
# Default: "smith"
harness = "smith"

# Hard kill switch. Set to false to disable the orchestrator even when
# `harness` is configured.
# Default: true
enabled = true

# ── Playbook ──────────────────────────────────────────────────────────────────
#
# The playbook is the shared Markdown space each session can run. Built-in
# templates (Blank, Tasks, Investigation, Goal) are always offered; drop your own
# `<name>.md` files in the templates directory to add custom templates. A custom
# template is just a Markdown file — its filename is its name and its contents are
# the playbook. Custom templates reload on every playbook open — no daemon restart
# needed.

# [playbook]
# Directory custom playbook templates are read from.
# Default: <data_dir>/playbook/templates  (e.g. ~/.local/share/construct/playbook/templates)
# The CONSTRUCT_PLAYBOOK_TEMPLATES_DIR env var overrides this.
# templates_dir = "/path/to/my/playbook-templates"

# ── Next-prompt suggestions ──────────────────────────────────────────────────
#
# When a user session's turn ends, the daemon generates a hand of suggested
# next prompts (spec 0109) with a one-shot model call over the session's
# transcript tail (smith for smith/shell sessions, the session's own harness
# otherwise). Best-effort: with no usable model the skip is reported via
# features.status (spec 0151) instead of generating.

# [suggest]
# Set to false to disable suggestion generation entirely.
# Default: true
# enabled = true

# ── Smith named model profiles ────────────────────────────────────────────────
#
# Named endpoint profiles for the smith harness. Reference at runtime with
# `/model @<name>` (or `--model @<name>`). Lets multiple endpoints of the
# same wire protocol coexist — unlike the single OPENAI_BASE_URL env var.
#
# `provider` is the wire protocol: openai | openai-responses | azure-openai |
# anthropic | gemini | meta | grok | ollama
#
# OAuth-backed providers (claude-oauth / codex-oauth / grok-oauth /
# kimi-oauth) are not configurable here — they have no base-URL/key surface.
#
# These profiles are ALSO the route targets used by [router] below: with
# routing enabled, each one appears in the TUI's route picker for any
# route-capable session. `openai` / `grok` / `anthropic` profiles are
# selectable from a `claude` session (the first two via translation);
# `meta` / `ollama` are shown with the reason they are not.

# OpenAI-compatible example (DeepSeek):
# [smith.models.deepseek]
# provider    = "openai"
# base_url    = "https://api.deepseek.com/v1"
# api_key_env = "DEEPSEEK_API_KEY"   # name of the env var holding the key (preferred)
# # api_key   = "sk-..."             # inline key (discouraged; use api_key_env)
# model       = "deepseek-chat"      # default model; overridable with @deepseek:<model>

# OpenAI-compatible example (Groq):
# [smith.models.groq]
# provider    = "openai"
# base_url    = "https://api.groq.com/openai/v1"
# api_key_env = "GROQ_API_KEY"
# model       = "llama-3.3-70b-versatile"

# Local Ollama:
# [smith.models.local]
# provider = "ollama"
# base_url = "http://localhost:11434"   # default Ollama port; omit to use the default
# model    = "llama3.1"                 # no api_key needed for Ollama

# Anthropic direct API:
# [smith.models.claude]
# provider    = "anthropic"
# api_key_env = "ANTHROPIC_API_KEY"
# model       = "claude-sonnet-4-6"

# Gemini direct API:
# [smith.models.gemini]
# provider    = "gemini"
# api_key_env = "GEMINI_API_KEY"
# model       = "gemini-2.5-pro"

# Azure OpenAI Responses API (the resource/deployment URL is account-specific):
# [smith.models.azure]
# provider    = "azure-openai"
# base_url    = "https://RESOURCE.openai.azure.com/openai"
# api_key_env = "AZURE_OPENAI_API_KEY"
# model       = "DEPLOYMENT_NAME"

# Meta Model API:
# [smith.models.meta]
# provider    = "meta"
# api_key_env = "META_API_KEY"   # MODEL_API_KEY is also accepted by default
# model       = "muse-spark-1.1"

# Grok / xAI direct API:
# [smith.models.grok]
# provider    = "grok"
# api_key_env = "GROK_API_KEY"   # or XAI_API_KEY
# model       = "grok-4.3"

# ── Environment variable reference ────────────────────────────────────────────
#
# These env vars are read by the daemon or adapters at runtime. They are NOT
# part of config.toml — set them in the shell that launches the daemon (or in
# a systemd unit / launchd plist / wrapper script).
#
# Path overrides (XDG-style):
#   CONSTRUCT_HOME         — base directory for config, state, data, and run path overrides
#   CONSTRUCT_CONFIG_DIR   — config directory  (default: $CONSTRUCT_HOME/config or ~/.config/construct)
#   CONSTRUCT_STATE_DIR    — state directory   (default: $CONSTRUCT_HOME/state or ~/.local/state/construct)
#   CONSTRUCT_DATA_DIR     — data directory    (default: $CONSTRUCT_HOME/data or ~/.local/share/construct)
#   CONSTRUCT_RUNTIME_DIR  — runtime directory (default: $CONSTRUCT_HOME/run or same as state dir)
#   XDG_CONFIG_HOME / XDG_STATE_HOME / XDG_DATA_HOME / XDG_RUNTIME_DIR also apply.
#
# Daemon:
#   CONSTRUCT_WEBUI_PORT      — pin local web UI port (default: reclaim
#                              runtime_dir/webui.port or 5746, auto-pick if busy)
#   CONSTRUCT_REMOTE_WS_PORT  — auto-start remote WS listener on this port at boot
#   CONSTRUCT_PLAYBOOK_TEMPLATES_DIR — playbook templates dir (overrides [playbook].templates_dir)
#
# Smith harness (can also be set per-adapter via [adapters.smith.env]):
#   CONSTRUCT_SMITH_MODEL         — default model (provider:name, @profile, or oauth prefix)
#   CONSTRUCT_SMITH_AUTOMODE      — set to "1" to enable autonomous mode by default
#   CONSTRUCT_SMITH_MAX_STEPS     — max tool-call steps per turn
#   CONSTRUCT_SMITH_MAX_TURN_SECS — max seconds per turn
#   CONSTRUCT_SMITH_HOOKS_JSON    — inline JSON hooks config
#   CONSTRUCT_SMITH_HOOKS_CONFIG  — path to a hooks config file
#   META_API_KEY / MODEL_API_KEY  — Meta Model API credential
#   META_BASE_URL                 — Meta Model API base URL override
#   CONSTRUCT_SHELL_BIN           — shell binary used by smith hooks
#
# Operator / orchestrator:
#   CONSTRUCT_OPERATOR_LOOP_DISABLED      — set to "1" to disable the ambient loop
#   CONSTRUCT_OPERATOR_MONITOR_MODEL      — model used for the ambient monitor
#   CONSTRUCT_OPERATOR_AMBIENT_LOOP_SECS  — ambient loop interval in seconds
#   CONSTRUCT_OPERATOR_ACTIVE_WINDOW_SECS — active-window duration in seconds
#   CONSTRUCT_LOOP_MIN_SECS               — minimum loop interval
#   CONSTRUCT_LOOP_MAX_SECS               — maximum loop interval
#
# Adapter CLI overrides (set in [adapters.<name>.env] or the outer shell):
#   CONSTRUCT_CLAUDE_CMD      — command prefix for the claude adapter
#   CONSTRUCT_CODEX_CMD       — command prefix for the codex adapter
#   CONSTRUCT_ANTIGRAVITY_CMD — command prefix for the antigravity adapter
#   CONSTRUCT_GROK_CMD        — command prefix for the grok adapter
#   CONSTRUCT_KIMI_CMD        — command prefix for the kimi adapter
#   CONSTRUCT_HERMES_CMD      — command prefix for the hermes adapter
#   CONSTRUCT_PI_CMD          — command prefix for the pi adapter
#   CONSTRUCT_SHELL_CMD       — command prefix for the shell adapter
#   CONSTRUCT_CLAUDE_BIN      — binary path fallback for the claude adapter
#   CONSTRUCT_CODEX_BIN       — binary path fallback for the codex adapter
#   CONSTRUCT_OPENCODE_BIN    — binary path fallback for the opencode adapter
#   CONSTRUCT_ANTIGRAVITY_BIN — binary path fallback for the antigravity adapter
#   CONSTRUCT_GROK_BIN        — binary path fallback for the grok adapter
#   CONSTRUCT_KIMI_BIN        — binary path fallback for the kimi adapter
#   CONSTRUCT_HERMES_BIN      — binary path fallback for the hermes adapter
#   CONSTRUCT_PI_BIN          — binary path fallback for the pi adapter
#
# ---------------------------------------------------------------------------
# Model routing (specs 0113/0114/0115/0116/0117)
# ---------------------------------------------------------------------------
# Automatic by default. Route-capable sessions are spawned with HTTPS_PROXY
# pointing at a loopback proxy the daemon owns, and supported harnesses receive
# a session-local native model catalog containing every usable route Construct
# detects. Subscription logins owned by Claude, Codex, and Grok are discovered
# read-only; no duplicate model configuration is required.
#
# The proxy does NOT replace where a harness sends native traffic. With model
# publication disabled it blind-tunnels every unarmed connection to the
# destination the harness resolved. A harness's endpoint configuration is
# never displaced.
#
# Arming a route (from the TUI: click the model in the modeline) redirects
# just that session's model traffic to the chosen endpoint, on the running
# session, with no restart. The choice persists across daemon restarts.
#
# For Codex, Construct merges available routes into a generated, session-local
# copy of Codex's model catalog and passes it as a command-line override. This
# makes routes available to the native model picker and native subagents
# without editing Codex's persistent config. Construct then inspects only Codex
# model requests: a published id selects its route per request; a native id
# keeps using Codex's own endpoint (or the manually armed session route).
# The generated catalog uses Codex's v1 multi-agent surface because v2 may
# encrypt child task text for ChatGPT, which a routed provider cannot decrypt.
#
# For Claude Code, Construct exposes a session-local Anthropic-compatible
# gateway and enables Claude's native gateway model discovery. `/model` and
# native subagents see every usable route as a "From gateway" entry. The
# gateway is loopback-only and capability-scoped to the session; Construct
# leaves an existing ANTHROPIC_BASE_URL untouched.
#
# Route targets are the [smith.models.*] profiles below — declare an
# endpoint once and it is reachable from both smith and a routed session.
# When the target's dialect differs from the harness's, the router
# translates through a canonical form. Anthropic Messages, OpenAI Chat
# Completions, OpenAI Responses (including Azure), and Google Gemini are
# supported. Providers with no translator — meta and Ollama's native API —
# are listed in the picker with that reason and cannot be selected. An
# OpenAI-compatible server (including Ollama's own /v1
# endpoint) can be reached by declaring it as `provider = "openai"` with
# its base_url.
#
# Subscription logins already on this machine (Claude, ChatGPT/Codex, Grok)
# are offered as route targets automatically — nothing to declare, because a
# login has no base URL or key to write down (spec 0117). The router READS
# those credentials and never refreshes them: refresh writes back to a store
# the owning CLI owns, and a second refresher can invalidate that tool's
# token mid-turn. An expired login is reported with the command to renew it.
#
# Antigravity's login is not offered: its backend speaks a Gemini-shaped
# protocol the router has no translator for.
#
# [router]
# enabled        = false # opt out of all model routing and publication
# publish_models = false # keep manual routing, but do not augment native pickers
# port           = 8917 # optional pin. When omitted the daemon reclaims the
#                       # port last bound by this home (runtime_dir/router.port),
#                       # falling back to 8917 and then a free port if busy.
#                       # Harness processes outlive the daemon and keep dialing
#                       # the port they were given at spawn, so the persisted
#                       # port is what makes restart safe without config.
#
# # Optional picker/subagent ordering. Each selector is `<route>/<model>`.
# # Codex exposes only its five lowest-priority catalog entries to spawn_agent;
# # use this list to choose that roster. Without it, native defaults retain
# # their order and routed entries use Codex's standard routed priority.
# featured_models = [
#   "claude-oauth/opus",
#   "codex-oauth/gpt-5.6-sol",
# ]
#
# [router.oauth]
# # Models each subscription login offers in the route picker. Optional:
# # without it, the models come from the same curated list that backs
# # smith's `/model` completion, so the two never disagree. Set this only to
# # narrow the choice or to use a model newer than that list.
# # One string pins a single model; a list becomes the picker's second step,
# # first entry the default.
# claude-oauth = ["opus", "sonnet"]
# codex-oauth  = ["gpt-5.6-sol", "gpt-5.5"]
# grok-oauth   = "grok-4.5"
# kimi-oauth   = "k3"
"#;

/// Kept for backwards-compat: `construct daemon default-config` and any
/// external code that imports this name still works.
pub const DEFAULT_CONFIG_TOML: &str = CONFIG_TOML_TEMPLATE;

/// Write (or overwrite) `config.toml.template` in the config directory.
/// Called on every daemon start so the template stays current after upgrades.
/// Failure is non-fatal — a warning is logged and the daemon continues.
pub fn write_template(paths: &Paths) {
    let path = paths.config_template_file();
    if let Err(e) = std::fs::write(&path, CONFIG_TOML_TEMPLATE) {
        tracing::warn!(path = %path.display(), error = %e, "could not write config.toml.template");
    } else {
        tracing::debug!(path = %path.display(), "wrote config.toml.template");
    }
}

/// Set (or clear) `[adapters.smith.env] CONSTRUCT_SMITH_MODEL` in the live
/// `config.toml`, preserving every other table/comment via a format-
/// preserving edit (`toml_edit`) — the `/configure` dialog's smith-auth tab
/// (spec 0069) is the only caller, and users may have hand-written
/// unrelated config alongside it. `model_spec: None` clears the pin,
/// restoring smith's default auto-detect ladder.
pub fn set_smith_model_pin(paths: &Paths, model_spec: Option<&str>) -> Result<()> {
    let path = paths.config_file();
    let existing = if path.exists() {
        std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?
    } else {
        String::new()
    };
    let mut doc = existing
        .parse::<toml_edit::DocumentMut>()
        .with_context(|| format!("parse {}", path.display()))?;
    let adapters = ensure_subtable(&mut doc, "adapters")?;
    let smith = ensure_subtable(adapters, "smith")?;
    let env = ensure_subtable(smith, "env")?;
    match model_spec {
        Some(spec) => {
            env.insert("CONSTRUCT_SMITH_MODEL", toml_edit::value(spec));
        }
        None => {
            env.remove("CONSTRUCT_SMITH_MODEL");
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    std::fs::write(&path, doc.to_string()).with_context(|| format!("write {}", path.display()))
}

/// Get-or-insert a subtable of `table`, marking a freshly-created one
/// implicit so it doesn't print its own `[key]` header when it exists only
/// to hold a deeper table (matches how `toml_edit` renders supertables of a
/// dotted path like `[adapters.smith.env]`).
fn ensure_subtable<'a>(
    table: &'a mut toml_edit::Table,
    key: &str,
) -> Result<&'a mut toml_edit::Table> {
    let entry = table.entry(key).or_insert_with(|| {
        let mut t = toml_edit::Table::new();
        t.set_implicit(true);
        toml_edit::Item::Table(t)
    });
    entry
        .as_table_mut()
        .ok_or_else(|| anyhow::anyhow!("`{key}` in config.toml is not a table"))
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub adapters: BTreeMap<String, AdapterConfig>,
    #[serde(default)]
    pub defaults: Defaults,
    #[serde(default)]
    pub orchestrator: OrchestratorConfig,
    #[serde(default)]
    pub playbook: PlaybookConfig,
    #[serde(default)]
    pub suggest: SuggestConfig,
    #[serde(default)]
    pub router: RouterConfig,
    /// Read for its `models` table only — route targets are the
    /// `[smith.models.*]` profiles (spec 0030).
    #[serde(default)]
    pub smith: SmithConfig,
}

/// Next-prompt suggestion generation (spec 0109).
#[derive(Debug, Clone, Deserialize)]
pub struct SuggestConfig {
    /// Kill switch for turn-end suggestion generation. Default: `true`
    /// (generation is best-effort; without a smith credential smith/shell
    /// sessions skip it and report the gap via features.status — spec
    /// 0151 — so the default costs nothing when unconfigured).
    #[serde(default = "default_suggest_enabled")]
    pub enabled: bool,
}

fn default_suggest_enabled() -> bool {
    true
}

impl Default for SuggestConfig {
    fn default() -> Self {
        Self {
            enabled: default_suggest_enabled(),
        }
    }
}

/// `[router]` — model-route transport (specs 0113/0114/0115). Enabled by
/// default so a harness launched through Construct automatically receives
/// the usable routes Construct discovers. Set `enabled = false` to inject
/// nothing and bind no listener. With model publication disabled, unarmed
/// traffic remains a blind byte tunnel.
///
/// Route *targets* are not declared here — they are the `[smith.models.*]`
/// profiles (spec 0030), so an endpoint is declared once and reachable
/// from both smith and a routed harness session.
#[derive(Debug, Clone, Deserialize)]
pub struct RouterConfig {
    #[serde(default = "default_router_enabled")]
    pub enabled: bool,
    /// Publish available routes into supported harnesses' native model
    /// catalogs automatically. This may be disabled independently when a
    /// user wants manual session routing but does not want native pickers
    /// augmented. Publication requires reading the request's model field
    /// on the harness's fixed model host; every other destination remains
    /// byte-transparent.
    #[serde(default = "default_publish_models")]
    pub publish_models: bool,
    /// Route/model selectors to prioritize in native delegation surfaces.
    ///
    /// A selector is the literal `<route>/<model>` pair shown in config and
    /// model metadata; model ids may themselves contain slashes. Codex
    /// exposes only its five lowest-priority catalog entries to
    /// `spawn_agent`; this list chooses that roster. When empty, native
    /// priorities are preserved and routes use the standard routed-model
    /// priority.
    #[serde(default)]
    pub featured_models: Vec<String>,
    /// Loopback port the router listens on.
    ///
    /// `None` (the default when the key is omitted) means: prefer the
    /// port this home last bound (`runtime_dir/router.port`), else the
    /// compiled default (`8917`), and if that is busy pick a free port
    /// and persist it. Harness processes outlive the daemon and keep
    /// dialing the port they were given at spawn, so reclaiming the
    /// *same home's* port across restarts is mandatory; auto-picking is
    /// what lets a second home coexist without config.
    ///
    /// `Some(port)` pins the port — no auto-fallback, no overwrite of
    /// the persisted file on success. `Some(0)` asks the OS (tests).
    #[serde(default)]
    pub port: Option<u16>,
    /// `[router.oauth]` — model each subscription login sends, keyed by
    /// provider name (`claude-oauth`, `codex-oauth`, `grok-oauth`,
    /// `kimi-oauth`).
    /// Optional: each provider has a built-in default, which may lag a
    /// vendor release. A subscription login has no base URL or key to
    /// declare, so this is the only thing there is to configure.
    #[serde(default)]
    pub oauth: BTreeMap<String, OauthModels>,
}

impl Default for RouterConfig {
    fn default() -> Self {
        Self {
            enabled: default_router_enabled(),
            publish_models: default_publish_models(),
            featured_models: Vec::new(),
            port: None,
            oauth: BTreeMap::new(),
        }
    }
}

/// `[smith]` — only the `models` table is read by the daemon. Smith parses
/// this same section itself for its own `/model @<name>` switching; the
/// daemon reads it so the router can offer the same endpoints as route
/// targets without a second place to declare them.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct SmithConfig {
    #[serde(default)]
    pub models: BTreeMap<String, ModelProfile>,
}

/// One `[smith.models.<name>]` entry (spec 0030).
#[derive(Debug, Clone, Deserialize)]
pub struct ModelProfile {
    /// Wire protocol: `openai` | `openai-responses` | `azure-openai` |
    /// `anthropic` | `gemini` | `meta` | `ollama` | `grok`.
    pub provider: String,
    #[serde(default)]
    pub base_url: Option<String>,
    #[serde(default)]
    pub api_key_env: Option<String>,
    #[serde(default)]
    pub api_key: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
}

impl ModelProfile {
    /// Endpoint base URL, falling back to the provider's default exactly
    /// as smith resolves it — the same profile must reach the same place
    /// whether it is used by smith or by a route.
    pub fn resolved_base_url(&self) -> Option<String> {
        if let Some(url) = self.base_url.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
            return Some(url.trim_end_matches('/').to_string());
        }
        let default = match self.provider.to_ascii_lowercase().as_str() {
            "openai" | "openai-responses" => "https://api.openai.com/v1",
            "anthropic" => "https://api.anthropic.com/v1",
            "grok" => "https://api.x.ai/v1",
            "gemini" | "google" => "https://generativelanguage.googleapis.com/v1beta",
            "meta" => "https://api.meta.ai/v1",
            "ollama" => "http://localhost:11434",
            _ => return None,
        };
        Some(default.to_string())
    }

    /// Env vars consulted when the profile names no credential, mirroring
    /// smith's per-provider fallbacks.
    fn default_key_envs(&self) -> &'static [&'static str] {
        match self.provider.to_ascii_lowercase().as_str() {
            "openai" | "openai-responses" => &["OPENAI_API_KEY"],
            "azure" | "azure-openai" => &["AZURE_OPENAI_API_KEY"],
            "anthropic" => &["ANTHROPIC_API_KEY"],
            "gemini" | "google" => &["GEMINI_API_KEY", "GOOGLE_API_KEY"],
            "meta" => &["META_API_KEY", "MODEL_API_KEY"],
            "grok" => &["GROK_API_KEY", "XAI_API_KEY"],
            _ => &[],
        }
    }

    /// Resolve the endpoint credential. `Err` carries a message fit to
    /// show in the picker as the route's `unavailable_reason`.
    pub fn resolve_api_key(&self) -> Result<String, String> {
        if let Some(var) = self
            .api_key_env
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
        {
            return std::env::var(var)
                .ok()
                .map(|v| v.trim().to_string())
                .filter(|v| !v.is_empty())
                .ok_or_else(|| format!("{var} is not set in the daemon's environment"));
        }
        if let Some(key) = self.api_key.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
            return Ok(key.to_string());
        }
        let defaults = self.default_key_envs();
        for var in defaults {
            if let Ok(v) = std::env::var(var) {
                let v = v.trim().to_string();
                if !v.is_empty() {
                    return Ok(v);
                }
            }
        }
        if defaults.is_empty() {
            // Ollama and friends need no credential.
            return Ok(String::new());
        }
        Err(format!(
            "no api_key_env, and none of {} is set",
            defaults.join(" / ")
        ))
    }
}

/// `[router.oauth] <provider>` accepts one model or a list of them. One
/// model is the common case; a list is what makes the picker's second step
/// worth having.
#[derive(Debug, Clone, Deserialize)]
#[serde(untagged)]
pub enum OauthModels {
    One(String),
    Many(Vec<String>),
}

impl OauthModels {
    pub fn to_vec(&self) -> Vec<String> {
        match self {
            OauthModels::One(m) => vec![m.clone()],
            OauthModels::Many(m) => m.clone(),
        }
    }
}

fn default_router_enabled() -> bool {
    true
}

fn default_publish_models() -> bool {
    true
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct PlaybookConfig {
    /// Directory playbook templates are read from. When unset, the daemon uses
    /// `<data_dir>/playbook/templates`. The `CONSTRUCT_PLAYBOOK_TEMPLATES_DIR`
    /// env var overrides this.
    #[serde(default)]
    pub templates_dir: Option<String>,
}

impl Config {
    /// Resolve the playbook-templates directory override. Precedence:
    /// `CONSTRUCT_PLAYBOOK_TEMPLATES_DIR` env > `[playbook].templates_dir` config >
    /// default (`None`, leaving the daemon's `data_dir/playbook/templates`).
    pub fn playbook_templates_dir_override(&self) -> Option<PathBuf> {
        let env = std::env::var(PLAYBOOK_TEMPLATES_DIR_ENV).ok();
        resolve_playbook_templates_dir(self, env.as_deref())
    }
}

/// Pure resolver for the playbook-templates directory override, separated from
/// the live env read so precedence (env > config > default) is unit-testable.
pub fn resolve_playbook_templates_dir(cfg: &Config, env_override: Option<&str>) -> Option<PathBuf> {
    if let Some(v) = env_override.map(str::trim).filter(|s| !s.is_empty()) {
        return Some(PathBuf::from(v));
    }
    cfg.playbook
        .templates_dir
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
}

#[derive(Debug, Clone, Deserialize)]
pub struct OrchestratorConfig {
    /// Which harness backs the daemon-created orchestrator session.
    /// `None` (TOML: `harness = ""` or `enabled = false`) disables
    /// the orchestrator entirely — clients then fall back to the
    /// static command palette. Default: `"smith"`.
    #[serde(default)]
    pub harness: Option<String>,
    /// Hard kill switch; set to `false` to disable the orchestrator
    /// even when `harness` is configured. Default: `true`.
    #[serde(default = "default_orchestrator_enabled")]
    pub enabled: bool,
}

fn default_orchestrator_enabled() -> bool {
    true
}

impl Default for OrchestratorConfig {
    fn default() -> Self {
        Self {
            harness: Some("smith".to_string()),
            enabled: true,
        }
    }
}

impl OrchestratorConfig {
    /// The effective harness name when the orchestrator is enabled.
    pub fn effective_harness(&self) -> Option<&str> {
        if !self.enabled {
            return None;
        }
        self.harness.as_deref().filter(|s| !s.is_empty())
    }
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct AdapterConfig {
    #[serde(default)]
    pub binary: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub args: Vec<String>,
    /// Extra environment variables to inject when spawning this
    /// adapter. Lets operators set per-harness defaults — e.g. a
    /// default model — from `config.toml` without touching the
    /// shell where the daemon launches. Merged INTO the per-session
    /// `env_with_meta` (see `daemon/src/session.rs`); existing
    /// per-session env takes precedence so an explicit
    /// `construct new --env KEY=VAL` still overrides.
    ///
    /// Example: pin every new smith session to use an explicit
    /// subscription-backed OAuth path instead of the heuristic fallback:
    ///
    /// ```toml
    /// [adapters.smith]
    /// env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5" }
    /// # or: env = { CONSTRUCT_SMITH_MODEL = "claude-oauth:sonnet" }
    /// # or: env = { CONSTRUCT_SMITH_MODEL = "grok-oauth:grok-2-latest" }
    /// ```
    #[serde(default)]
    pub env: HashMap<String, String>,
    /// The interactive slash command a usage-probe session sends to capture
    /// this harness's own usage/status panel (spec 0086). TOML has no
    /// `null` literal, so "absent" and "explicitly unset" collapse to the
    /// same state; the three-way split is: absent (`None` here) → the
    /// built-in default command for this harness; explicit `""` → probe
    /// disabled; any other string → sent verbatim instead of the default.
    /// Resolve via [`Config::effective_usage_probe`], never this field
    /// directly.
    #[serde(default)]
    pub usage_probe: Option<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Defaults {
    #[serde(default)]
    pub worktree: Option<bool>,
}

pub struct BuiltinAdapter {
    pub name: &'static str,
    pub binary: &'static str,
    pub args: &'static [&'static str],
    pub description: &'static str,
}

pub const BUILTIN_ADAPTERS: &[BuiltinAdapter] = &[
    BuiltinAdapter {
        name: "shell",
        binary: "construct",
        args: &["__adapter", "shell"],
        description: "Generic shell command runner",
    },
    BuiltinAdapter {
        name: "claude",
        binary: "construct",
        args: &["__adapter", "claude"],
        description: "Claude Code",
    },
    BuiltinAdapter {
        name: "codex",
        binary: "construct",
        args: &["__adapter", "codex"],
        description: "OpenAI Codex",
    },
    BuiltinAdapter {
        name: "opencode",
        binary: "construct",
        args: &["__adapter", "opencode"],
        description: "OpenCode",
    },
    BuiltinAdapter {
        name: "agy",
        binary: "construct",
        args: &["__adapter", "agy"],
        description: "Google Antigravity",
    },
    BuiltinAdapter {
        name: "grok",
        binary: "construct",
        args: &["__adapter", "grok"],
        description: "Grok CLI",
    },
    BuiltinAdapter {
        name: "kimi",
        binary: "construct",
        args: &["__adapter", "kimi"],
        description: "Kimi Code",
    },
    BuiltinAdapter {
        name: "hermes",
        binary: "construct",
        args: &["__adapter", "hermes"],
        description: "Hermes Agent",
    },
    BuiltinAdapter {
        name: "pi",
        binary: "construct",
        args: &["__adapter", "pi"],
        description: "pi coding agent",
    },
    BuiltinAdapter {
        name: "smith",
        binary: "construct",
        args: &["__adapter", "smith"],
        description:
            "Built-in multi-provider agent (OpenAI / Anthropic / Gemini / Meta / Ollama / Grok)",
    },
];

/// Built-in usage-probe command for each harness that has an interactive
/// usage/status slash command (spec 0086). Harnesses not listed here
/// (`shell`, `smith`) have no probe unless an operator sets `usage_probe`
/// explicitly in `config.toml`.
const DEFAULT_USAGE_PROBE: &[(&str, &str)] = &[
    ("claude", "/usage"),
    ("codex", "/status"),
    ("agy", "/usage"),
    // Bare "/usage" opens grok's usage menu without picking an action;
    // "show" is the subcommand that actually renders the limits panel
    // (confirmed live: an invalid `/usage <x>` argument error message
    // points at exactly "/usage show" or "/usage manage").
    ("grok", "/usage show"),
    ("hermes", "/usage"),
];

fn default_usage_probe(harness: &str) -> Option<&'static str> {
    DEFAULT_USAGE_PROBE
        .iter()
        .find(|(name, _)| *name == harness)
        .map(|(_, cmd)| *cmd)
}

impl Config {
    /// The command a usage-probe session should send for `harness`
    /// (spec 0086), or `None` when probing is disabled for it. Mirrors the
    /// empty-string-means-unset convention `OrchestratorConfig::effective_harness`
    /// uses: an explicit `usage_probe = ""` disables the probe, an absent
    /// field falls back to the harness's built-in default command (see
    /// [`DEFAULT_USAGE_PROBE`]), and any other string is sent verbatim.
    pub fn effective_usage_probe(&self, harness: &str) -> Option<&str> {
        match self.adapters.get(harness).and_then(|a| a.usage_probe.as_deref()) {
            Some(s) if !s.is_empty() => Some(s),
            Some(_) => None, // explicit "" -> disabled
            None => default_usage_probe(harness),
        }
    }

    pub fn load_or_default(paths: &Paths) -> Result<Self> {
        let path = paths.config_file();
        let mut cfg = if path.exists() {
            let s = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            toml::from_str::<Config>(&s).with_context(|| format!("parse {}", path.display()))?
        } else {
            Self::default()
        };
        merge_builtin_adapters(&mut cfg);
        Ok(cfg)
    }
}

/// Layer in built-ins so users don't have to declare them.
///
/// Important: we layer at the FIELD level, not the entry level — a user who
/// declared `[adapters.smith] env = {...}` (only to set per-harness env
/// defaults) still needs the builtin `binary` + `description` to fill in.
/// Without this, declaring an `[adapters.<name>]` block to set ONE field
/// would silently drop the builtin's binary path and the daemon would fail
/// with "adapter binary not found" on session create.
///
/// Separate from [`Config::load_or_default`] so `doctor` can apply the same
/// layering to a `Config::default()` when the user's file failed to parse,
/// and still report on the harnesses that would exist (spec 0168).
pub(crate) fn merge_builtin_adapters(cfg: &mut Config) {
    for b in BUILTIN_ADAPTERS {
        let entry = cfg.adapters.entry(b.name.to_string()).or_default();
        if entry.binary.is_none() {
            entry.binary = Some(b.binary.to_string());
        }
        if entry.args.is_empty() {
            entry.args = b.args.iter().map(|s| s.to_string()).collect();
        }
        if entry.description.is_none() {
            entry.description = Some(b.description.to_string());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_paths(tmp: &std::path::Path) -> Paths {
        Paths {
            config_dir: tmp.to_path_buf(),
            state_dir: tmp.to_path_buf(),
            data_dir: tmp.to_path_buf(),
            runtime_dir: tmp.to_path_buf(),
        }
    }

    #[test]
    fn router_defaults_to_automatic_model_publication() {
        let cfg: Config = toml::from_str("").expect("parse");
        assert!(cfg.router.enabled);
        assert!(cfg.router.publish_models);
        assert_eq!(cfg.router.port, None, "omitted port means auto-allocate");
    }

    #[test]
    fn partial_router_table_keeps_automatic_defaults() {
        let cfg: Config = toml::from_str(
            r#"
                [router]
                port = 18918
            "#,
        )
        .expect("parse");
        assert!(cfg.router.enabled);
        assert!(cfg.router.publish_models);
        assert_eq!(cfg.router.port, Some(18918));

        let opted_out: Config = toml::from_str(
            r#"
                [router]
                publish_models = false
            "#,
        )
        .expect("parse");
        assert!(opted_out.router.enabled);
        assert!(!opted_out.router.publish_models);
    }

    /// The `/configure` dialog's smith-auth tab (spec 0069) writes through
    /// this function — it must round-trip the pin and leave everything else
    /// in the file untouched (comments, unrelated tables).
    #[test]
    fn set_smith_model_pin_writes_and_preserves_unrelated_content() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let paths = tmp_paths(tmp.path());
        std::fs::write(
            paths.config_file(),
            "# a comment worth keeping\n[defaults]\nworktree = true\n",
        )
        .expect("write");

        set_smith_model_pin(&paths, Some("claude-oauth:claude-sonnet-4-6")).expect("set pin");
        let written = std::fs::read_to_string(paths.config_file()).expect("read");
        assert!(written.contains("# a comment worth keeping"));
        assert!(written.contains("[defaults]"));
        assert!(written.contains("worktree = true"));
        assert!(written.contains("[adapters.smith.env]"));
        assert!(written.contains(r#"CONSTRUCT_SMITH_MODEL = "claude-oauth:claude-sonnet-4-6""#));

        set_smith_model_pin(&paths, None).expect("clear pin");
        let cleared = std::fs::read_to_string(paths.config_file()).expect("read");
        assert!(!cleared.contains("CONSTRUCT_SMITH_MODEL"));
        assert!(cleared.contains("# a comment worth keeping"));
        assert!(cleared.contains("worktree = true"));
    }

    /// No pre-existing `config.toml` (fresh install): the write creates the
    /// config dir and file rather than erroring.
    #[test]
    fn set_smith_model_pin_creates_file_when_absent() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let paths = tmp_paths(&tmp.path().join("nested"));
        set_smith_model_pin(&paths, Some("ollama:llama3.1")).expect("set pin");
        let written = std::fs::read_to_string(paths.config_file()).expect("read");
        assert!(written.contains(r#"CONSTRUCT_SMITH_MODEL = "ollama:llama3.1""#));
    }

    /// `[adapters.<name>].env` parses out of TOML and lands on the
    /// resolved AdapterConfig.
    #[test]
    fn adapter_env_table_parses() {
        let toml = r#"
            [adapters.smith]
            binary = "construct-adapter-smith"
            env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5", DEBUG = "1" }
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert_eq!(
            smith.env.get("CONSTRUCT_SMITH_MODEL").map(String::as_str),
            Some("codex-oauth:gpt-5.5"),
        );
        assert_eq!(smith.env.get("DEBUG").map(String::as_str), Some("1"));
    }

    /// Omitting `env` is fine — it defaults to empty rather than
    /// failing the parse.
    #[test]
    fn adapter_env_defaults_to_empty() {
        let toml = r#"
            [adapters.smith]
            binary = "construct-adapter-smith"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert!(smith.env.is_empty());
    }

    /// REGRESSION: declaring `[adapters.smith] env = {…}` (to set
    /// per-harness env defaults — the motivating use case for that
    /// field) must NOT drop the built-in `binary` / `description`
    /// values that the daemon needs to actually spawn the adapter.
    ///
    /// Before this fix, the BUILTIN_ADAPTERS layer used
    /// `or_insert_with`, which only fired when the entry was
    /// missing entirely. A user-supplied entry that lacked `binary`
    /// got NO `binary` field, the daemon fell back to looking up a
    /// binary named bare `smith` (not `construct-adapter-smith`),
    /// and session create failed with "adapter binary not found".
    #[test]
    fn user_partial_adapter_config_keeps_builtin_binary() {
        let toml = r#"
            [adapters.smith]
            env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5" }
        "#;
        let mut cfg: Config = toml::from_str(toml).expect("parse");
        // Mimic Config::load's builtin-layering step (the actual
        // load() walks the filesystem, which we'd rather not in
        // tests).
        for b in BUILTIN_ADAPTERS {
            let entry = cfg.adapters.entry(b.name.to_string()).or_default();
            if entry.binary.is_none() {
                entry.binary = Some(b.binary.to_string());
            }
            if entry.args.is_empty() {
                entry.args = b.args.iter().map(|s| s.to_string()).collect();
            }
            if entry.description.is_none() {
                entry.description = Some(b.description.to_string());
            }
        }
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert_eq!(
            smith.binary.as_deref(),
            Some("construct"),
            "user-supplied [adapters.smith] with only `env` set must still pick up the built-in binary path",
        );
        // And the user's env stays in place.
        assert_eq!(
            smith.env.get("CONSTRUCT_SMITH_MODEL").map(String::as_str),
            Some("codex-oauth:gpt-5.5"),
        );
    }

    #[test]
    fn builtin_harness_descriptions_omit_wrapper_implementation_details() {
        assert!(BUILTIN_ADAPTERS
            .iter()
            .all(|adapter| !adapter.description.contains("wraps the")));
        assert!(!CONFIG_TOML_TEMPLATE.contains("wraps the"));
    }

    /// `[playbook].templates_dir` parses out of TOML.
    #[test]
    fn playbook_templates_dir_parses() {
        let toml = r#"
            [playbook]
            templates_dir = "/srv/playbook-templates"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        assert_eq!(
            cfg.playbook.templates_dir.as_deref(),
            Some("/srv/playbook-templates")
        );
    }

    /// Resolution precedence: env override > `[playbook].templates_dir` > default.
    #[test]
    fn resolve_playbook_templates_dir_precedence() {
        let mut cfg = Config::default();

        // Default: no env, no config → None (daemon uses data_dir/playbook/templates).
        assert_eq!(resolve_playbook_templates_dir(&cfg, None), None);

        // Config only.
        cfg.playbook.templates_dir = Some("/from/config".to_string());
        assert_eq!(
            resolve_playbook_templates_dir(&cfg, None),
            Some(PathBuf::from("/from/config")),
        );

        // Env wins over config.
        assert_eq!(
            resolve_playbook_templates_dir(&cfg, Some("/from/env")),
            Some(PathBuf::from("/from/env")),
        );

        // Blank/whitespace values are ignored (fall through to the next source).
        assert_eq!(
            resolve_playbook_templates_dir(&cfg, Some("   ")),
            Some(PathBuf::from("/from/config")),
        );
        cfg.playbook.templates_dir = Some("  ".to_string());
        assert_eq!(resolve_playbook_templates_dir(&cfg, Some("")), None);
    }

    /// `Config::effective_usage_probe` (spec 0086): absent `usage_probe`
    /// falls back to the harness's built-in default command; a harness with
    /// no built-in default (and no override) has probing disabled.
    #[test]
    fn effective_usage_probe_absent_falls_back_to_builtin_default() {
        let cfg = Config::default();
        assert_eq!(cfg.effective_usage_probe("claude"), Some("/usage"));
        assert_eq!(cfg.effective_usage_probe("codex"), Some("/status"));
        assert_eq!(cfg.effective_usage_probe("agy"), Some("/usage"));
        assert_eq!(cfg.effective_usage_probe("grok"), Some("/usage show"));
        assert_eq!(cfg.effective_usage_probe("hermes"), Some("/usage"));
        // No built-in default and no override -> disabled.
        assert_eq!(cfg.effective_usage_probe("shell"), None);
        assert_eq!(cfg.effective_usage_probe("smith"), None);
    }

    #[test]
    fn kimi_is_registered_as_a_builtin_wrapper() {
        let adapter = BUILTIN_ADAPTERS
            .iter()
            .find(|adapter| adapter.name == "kimi")
            .expect("kimi builtin");
        assert_eq!(adapter.binary, "construct");
        assert_eq!(adapter.args, &["__adapter", "kimi"]);
    }

    #[test]
    fn hermes_is_registered_as_a_builtin_wrapper() {
        let adapter = BUILTIN_ADAPTERS
            .iter()
            .find(|adapter| adapter.name == "hermes")
            .expect("hermes builtin");
        assert_eq!(adapter.binary, "construct");
        assert_eq!(adapter.args, &["__adapter", "hermes"]);
        assert_eq!(default_usage_probe("hermes"), Some("/usage"));
    }

    #[test]
    fn pi_is_registered_as_a_builtin_wrapper() {
        let adapter = BUILTIN_ADAPTERS
            .iter()
            .find(|adapter| adapter.name == "pi")
            .expect("pi builtin");
        assert_eq!(adapter.binary, "construct");
        assert_eq!(adapter.args, &["__adapter", "pi"]);
    }

    #[test]
    fn opencode_is_registered_as_a_builtin_wrapper() {
        let adapter = BUILTIN_ADAPTERS
            .iter()
            .find(|adapter| adapter.name == "opencode")
            .expect("opencode builtin");
        assert_eq!(adapter.binary, "construct");
        assert_eq!(adapter.args, &["__adapter", "opencode"]);
    }

    /// Explicit `usage_probe = ""` disables the probe even though the
    /// harness has a built-in default — TOML has no null literal, so this
    /// is the only way to represent "explicitly off".
    #[test]
    fn effective_usage_probe_empty_string_disables() {
        let toml = r#"
            [adapters.claude]
            usage_probe = ""
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        assert_eq!(cfg.effective_usage_probe("claude"), None);
    }

    /// Any other string overrides the built-in default verbatim.
    #[test]
    fn effective_usage_probe_override_string_wins() {
        let toml = r#"
            [adapters.codex]
            usage_probe = "/status --verbose"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        assert_eq!(
            cfg.effective_usage_probe("codex"),
            Some("/status --verbose")
        );
    }
}
